module.exports = SHOP_DATA = [
  {
    id: 1,
    title: "Hats",
    routeName: "hats",
    imageUrl: "/images/gray.jpg",
    items: [
      {
        id: 1,
        name: "Tan Brim",
        imageUrl: "/images/tanbrim.jpg",
        price: 25,
      },
      {
        id: 2,
        name: "Yellow Beanie",
        imageUrl: "/images/yellowBeanie.jpg",
        price: 18,
      },
      {
        id: 3,
        name: "Hiker's Hat",
        imageUrl: "/images/hikershat.jpg",
        price: 35,
      },
      {
        id: 4,
        name: "Black Trim",
        imageUrl: "/images/blackTrimtan.jpg",
        price: 25,
      },
      {
        id: 5,
        name: "Blue W Snapback",
        imageUrl: "/images/blueW.jpg",
        price: 18,
      },
      {
        id: 6,
        name: "Palm Tree Cap",
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        price: 14,
      },
      {
        id: 7,
        name: "Red Beanie",
        imageUrl: "/images/redBeanie.jpg",
        price: 18,
      },
      {
        id: 8,
        name: "Wolf Cap",
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 14,
      },
    ],
  },
  {
    id: 2,
    title: "Sneakers",
    routeName: "sneakers",
    imageUrl: "/images/redblackairs.jpg",
    items: [
      {
        id: 9,
        name: "Adidas Ultraboosts",
        imageUrl: "/images/ultraBoosts.jpg",
        price: 220,
      },
      {
        id: 10,
        name: "Adidas Yeezy",
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
      },
      {
        id: 11,
        name: "Green Vans",
        imageUrl: "/images/greenVans.jpg",
        price: 110,
      },
      {
        id: 12,
        name: "Nike White AirForce",
        imageUrl: "/images/blackSwoosh.jpg",
        price: 160,
      },
      {
        id: 13,
        name: "Nike Red High Tops",
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 160,
      },
      {
        id: 14,
        name: "Nike Brown High Tops",
        imageUrl: "/images/brown&Black.jpg",
        price: 160,
      },
      {
        id: 15,
        name: "Air Jordan Limited",
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
      },
      {
        id: 16,
        name: "Timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
      },
    ],
  },
  {
    id: 3,
    title: "Jackets",
    routeName: "jackets",
    imageUrl: "/images/jackets.jpg",
    items: [
      {
        id: 17,
        name: "Black Jean Shearling",
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        price: 125,
      },
      {
        id: 18,
        name: "Blue Jean Jacket",
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        price: 90,
      },
      {
        id: 19,
        name: "Grey Jean Jacket",
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        price: 90,
      },
      {
        id: 20,
        name: "Brown Shearling",
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        price: 165,
      },
      {
        id: 21,
        name: "Tan Trench",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 185,
      },
      {
        id: 22,
        name: "Green Bomber",
        imageUrl: "/images/greenbomber.jpg",
        price: 200,
      },
      {
        id: 23,
        name: "Jean Jacket",
        imageUrl: "/images/jeanjacket.jpg",
        price: 50,
      },
      {
        id: 24,
        name: "White Cardigan",
        imageUrl: "/images/whiteCardigan.jpg",
        price: 80,
      },
    ],
  },
  {
    id: 4,
    title: "Womens",
    routeName: "womens",
    imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
    items: [
      {
        id: 25,
        name: "Blue Tanktop",
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        price: 25,
      },
      {
        id: 26,
        name: "Floral Blouse",
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        price: 20,
      },
      {
        id: 27,
        name: "Floral Dress",
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        price: 80,
      },
      {
        id: 28,
        name: "Red Dots Dress",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        price: 80,
      },
      {
        id: 29,
        name: "Striped Sweater",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        price: 45,
      },
      {
        id: 30,
        name: "Yellow Track Suit",
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        price: 135,
      },
      {
        id: 31,
        name: "Trench Coat",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 100,
      },
      {
        id: 32,
        name: "Leather Jacket",
        imageUrl: "/images/blackLeather.jpg",
        price: 200,
      },
    ],
  },
  {
    id: 5,
    title: "Mens",
    routeName: "mens",
    imageUrl: "/images/men.jpg",
    items: [
      {
        id: 33,
        name: "Camo Down Vest",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 325,
      },
      {
        id: 34,
        name: "Floral T-shirt",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 20,
      },
      {
        id: 35,
        name: "Balanced Longsleeve",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 25,
      },
      {
        id: 36,
        name: "Pink T-shirt",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 25,
      },
      {
        id: 37,
        name: "Jean Long Sleeve",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 40,
      },
      {
        id: 38,
        name: "Burgundy T-shirt",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 25,
      },
      {
        id: 39,
        name: "Blue Sweater",
        imageUrl: "/images/blueSweater.jpg",
        price: 25,
      },
      {
        id: 40,
        name: "Red Snow Jacket",
        imageUrl: "/images/redsnowjacket.jpg",
        price: 200,
      },
    ],
  },
];
